USE [master]
GO

/****** Object:  Database [aeropuertos_pr]    Script Date: 5/11/2021 2:37:46 a. m. ******/
CREATE DATABASE [aeropuertos_pr]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'aeropuertos_pr', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\aeropuertos_pr.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'aeropuertos_pr_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\aeropuertos_pr_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [aeropuertos_pr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [aeropuertos_pr] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET ARITHABORT OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [aeropuertos_pr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [aeropuertos_pr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET  DISABLE_BROKER 
GO

ALTER DATABASE [aeropuertos_pr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [aeropuertos_pr] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET RECOVERY FULL 
GO

ALTER DATABASE [aeropuertos_pr] SET  MULTI_USER 
GO

ALTER DATABASE [aeropuertos_pr] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [aeropuertos_pr] SET DB_CHAINING OFF 
GO

ALTER DATABASE [aeropuertos_pr] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [aeropuertos_pr] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [aeropuertos_pr] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [aeropuertos_pr] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [aeropuertos_pr] SET QUERY_STORE = OFF
GO

ALTER DATABASE [aeropuertos_pr] SET  READ_WRITE 
GO

